require: rubocop-performance

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - '.rblcl/**/*'
    - '.git/**/*'
    - '.vscode/**/*'
    - 'config/**/*'
  TargetRubyVersion: 3.0.0
  NewCops: enable

Documentation:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Layout/LineLength:
  Max: 170

# Style/NumericLiterals:
#   MinDigits: 15

# Layout/SpaceBeforeBlockBraces:
#   EnforcedStyle: space

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 50

# Metrics/BlockLength:
#   Max: 50

Metrics/ClassLength:
  Max: 250

# Style/AsciiComments:
#   Enabled: false

# Style/ClassAndModuleChildren:
#   Enabled: false

# Metrics/ParameterLists:
#   Enabled: false

Lint/FloatComparison:
    Enable: false

Layout/EndOfLine:
  Enabled: false

Metrics/AbcSize:
  Max: 18 

Naming/MethodParameterName:
  Enabled: false


Metrics/CyclomaticComplexity:
  Max: 7

Style/HashLikeCase:
    Enabled: false

# Single quotes being faster is hardly measurable and only affects parse time.
# Enforcing double quotes reduces the times where you need to change them
# when introducing an interpolation. Use single quotes only if their semantics
# are needed.
Style/StringLiterals:
  EnforcedStyle: double_quotes

# We do not need to support Ruby 1.9, so this is good to use.
Style/SymbolArray:
  Enabled: true

# Layout/SpaceAroundOperators:
#   Enabled: false

# inherit_gem:
#   rubocop-config-prettier: config/rubocop.yml
