---
include:
- "**/*.rb"
exclude:
- Prove/**/*
- Ruby/**/*
- spec/**/*
- TEST/**/*
- test/**/*
- vendor/**/*
- ".git/**/*"
- ".logs/**/*"
- ".rblcl/**/*"
- ".yardoc/**/*"
- "doc/**/*"
require: []
domains: []
reporters:
- rubocop
max_files: 5000
