---
include:
- "**/*.rb"
exclude:
- Prove/**/*
- Ruby/**/*
- spec/**/*
- TEST/**/*
- test/**/*
- vendor/**/*
- doc/**/*
- "doc/**/*"
- ".git/**/*"
- ".logs/**/*"
- ".rblcl/**/*"
- ".yardoc/**/*"
require: []
domains: []
reporters:
- rubocop
max_files: 5000
