---
include:
- "app/**/*.rb"
- "lib/**/*.rb"
exclude:
- Prove/**/*
- Ruby/**/*
- spec/**/*
- TEST/**/*
- DB/**/
- test/**/*
- vendor/**/*
- doc/**/*
- "doc/**/*"
- ".git/**/*"
- ".logs/**/*"
- ".rblcl/**/*"
- ".yardoc/**/*"
require:
- "functional-light-service"
domains: []
reporters:
- rubocop
max_files: 5000
