defaults: &defaults

  mail:
    from: 'michele.boscolo@eni.com'
    to: 'michele.boscolo@eni.com'
    server: 'relay.eni.pri'
    port: 25

  path:
    root: '../'
    db: '../DB/'
    consuntivi_pdf: '../report/consuntivi/'
    forecast_pdf: '../report/forecast/'
  
  file:
    excel_forecast: 'Forecast.xlsm'
    db_xls: 'DB.xlsm'
    db2_xls: 'DB2.xlsm'
    db_csv: 'DB2.csv'


development:
  <<: *defaults


test:
  <<: *defaults

production:
  <<: *defaults


production_local:
  <<: *defaults


