defaults: &defaults
  mail:
    from: 'michele.boscolo@ttpc.eni.com'
    to: 'michele.boscolo@ttpc.eni.com'
    cc: 'michele.boscolo@ttpc.eni.com'
    server: 'relay.eni.pri'
    port: 25

  path:
    root: '../'
    db: '../DB/'
    consuntivi_pdf: '../report/consuntivi/'
    forecast_pdf: '../report/forecast/'
    scada: '../Consuntivi/'
  
  file:
    excel_forecast: 'Forecast.xlsm'
    db_xls: 'DB.xlsm'
    db2_xls: 'DB2.xlsm'
    db_csv: 'DB2.csv'
    bat_dowload_scada: 'SyncToRemoteScript.bat'

development:
  <<: *defaults


test:
  <<: *defaults

production:
  <<: *defaults
  mail:
    from: "michele.boscolo@ttpc.eni.com"
    to: "Roberto.Pozzer@ttpc.eni.com"
    cc: "michele.boscolo@ttpc.eni.com; MohamedAli.Gattoufi@ttpc.eni.com; wassim.ouelhazi@ttpc.eni.com"


production_local:
  <<: *defaults


